# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgz9myJ11b3TAJKOXfhcNZmp7ObjxCVx
"""

# -*- coding: utf-8 -*-
"""
MFT105 期末专案：股票筛选与排名器（模型类）
作者：[张晨煦，王滢]
日期：2026年
"""

import yfinance as yf
import pandas as pd
import numpy as np

# ===================== 股票池 =====================
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "JPM", "V", "KO", "PG", "WMT", "JNJ",
    "600519.SS", "600036.SS", "300750.SZ",
    "0700.HK", "0005.HK"
]

# ===================== 数据获取 =====================
def fetch_stock_data(tickers):
    stock_data = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info
            hist = stock.history(period="1y")
            close_prices = hist["Close"]

            pe_ratio = info.get("trailingPE", np.nan)
            pb_ratio = info.get("priceToBook", np.nan)
            roe = info.get("returnOnEquity", np.nan)
            debt_ratio = info.get("debtToEquity", np.nan)
            annual_return = (close_prices.iloc[-1] / close_prices.iloc[0]) - 1
            volatility = close_prices.pct_change().std() * np.sqrt(252)
            dividend_yield = info.get("dividendYield", 0)

            stock_data.append({
                "代码": ticker,
                "名称": info.get("longName", ticker),
                "市盈率(PE)": pe_ratio,
                "市净率(PB)": pb_ratio,
                "净资产收益率(ROE)": roe,
                "资产负债率(%)": debt_ratio,
                "1年收益率": annual_return,
                "年化波动率": volatility,
                "股息率": dividend_yield
            })
        except Exception as e:
            continue
    return pd.DataFrame(stock_data)

# ===================== 评分模型 =====================
def calculate_scores(df):
    df_scored = df.copy().dropna()

    df_scored["估值得分"] = (df_scored["市盈率(PE)"].rank(ascending=False) +
                            df_scored["市净率(PB)"].rank(ascending=False)) / 2
    df_scored["品质得分"] = (df_scored["净资产收益率(ROE)"].rank(ascending=True) +
                            df_scored["资产负债率(%)"].rank(ascending=False)) / 2
    df_scored["动能得分"] = df_scored["1年收益率"].rank(ascending=True)
    df_scored["风险得分"] = df_scored["年化波动率"].rank(ascending=False)

    for col in ["估值得分", "品质得分", "动能得分", "风险得分"]:
        df_scored[col] = (df_scored[col] / df_scored[col].max()) * 10

    df_scored["综合得分"] = (df_scored["估值得分"] + df_scored["品质得分"] +
                            df_scored["动能得分"] + df_scored["风险得分"]) / 4
    df_scored = df_scored.sort_values("综合得分", ascending=False)
    df_scored["排名"] = range(1, len(df_scored) + 1)
    return df_scored

# ===================== 选股理由 =====================
def generate_reason(row):
    reasons = []
    if row["估值得分"] >= 8:
        reasons.append("估值极具吸引力")
    elif row["估值得分"] >= 6:
        reasons.append("估值合理")
    if row["品质得分"] >= 8:
        reasons.append("财务状况非常健康")
    elif row["品质得分"] >= 6:
        reasons.append("财务状况良好")
    if row["动能得分"] >= 8:
        reasons.append("近期走势强劲")
    elif row["动能得分"] >= 6:
        reasons.append("近期走势稳健")
    if row["风险得分"] >= 8:
        reasons.append("风险极低")
    elif row["风险得分"] >= 6:
        reasons.append("风险可控")
    if not reasons:
        reasons.append("指标均衡")
    return "; ".join(reasons)

# ===================== 主程序（输出绝对整齐） =====================
if __name__ == "__main__":
    print("="*88)
    print("               MFT105 期末专案：股票筛选与排名器（模型类）")
    print("="*88)

    print("\n正在获取股票数据...")
    df_stocks = fetch_stock_data(tickers)

    if not df_stocks.empty:
        print("正在计算综合得分...")
        df_result = calculate_scores(df_stocks)
        df_result["选股理由"] = df_result.apply(generate_reason, axis=1)

        # 整齐输出关键（固定宽度格式）
        final_columns = ["排名", "代码", "名称", "综合得分",
                          "市盈率(PE)", "净资产收益率(ROE)", "1年收益率", "年化波动率", "选股理由"]
        df_final = df_result[final_columns].round(2)

        print("\n【最终筛选结果】")
        print("-" * 88)

        # 表头（固定宽度）
        print(f"{'排名':<5}{'代码':<12}{'名称':<28}{'综合得分':<10}{'PE':<10}{'ROE':<10}{'收益率':<10}{'波动率':<10}{'选股理由':<20}")
        print("-" * 88)

        # 每行严格对齐
        for _, r in df_final.iterrows():
            print(f"{r['排名']:<5}{r['代码']:<12}{r['名称'][:26]:<28}{r['综合得分']:<10}{r['市盈率(PE)']:<10}{r['净资产收益率(ROE)']:<10}{r['1年收益率']:<10.2%}{r['年化波动率']:<10.2f}{r['选股理由']:<20}")

        print("-" * 88)

        # 基准对照
        print("\n【基准对照】")
        bench_ret = df_stocks["1年收益率"].mean()
        top3_ret = df_result.head(3)["1年收益率"].mean()
        print(f"股票池平均收益率: {bench_ret:.2%}")
        print(f"排名前三平均收益率: {top3_ret:.2%}")
        print(f"模型跑赢基准: {top3_ret - bench_ret:.2%}")